
translations: list[tuple[str, str]] = [
    ('approach', 'Aðferð'),
    ('Phenomena', 'Fyrirbæri'),
    ('Persist', 'Halda áfram'),
    ('Perception', 'Skynjun'),
    ('Audacity', 'Dirfska'),
    ('Sphere', 'Hnöttur'),
    ('Principle', 'Lögmál'),
    ('Constructive', 'Uppbygilegt'),
    ('Correspond', 'Samsvarar'),
    ('Ancient', 'Gamalt'),
    ('Marvel', 'Undur'),
    ('Feud', 'Deilur'),
    ('Reconstruction', 'Uppbygging'),
    ('Ambitions', 'Metnaður'),
    ('Destitute', 'Fátekur'),
    ('Evolution', 'Þróun'),
    ('Notorious', 'Illræmdur'),
    ('Blunder', 'Mistök'),
    ('Predator', 'Rándýr'),
    ('Prey', 'Bráð'),
    ('Excessive', 'Óhóflegt'),
    ('Intimidation', 'Ógn'),
    ('Relief', 'Léttir'),
    ('Devour', 'Gleypa í sig'),
    ('humble', 'Hógvær'),
]