translations: list[tuple[str, str]] = [
    # Unit 1
    ('approach', 'Aðferð'),
    ('Phenomena', 'Fyrirbæri'),
    ('Persist', 'Halda áfram'),
    ('Perception', 'Skynjun'),
    ('Audacity', 'Dirfska'),
    ('Sphere', 'Hnöttur'),
    ('Principle', 'Lögmál'),
    ('Constructive', 'Uppbygilegt'),
    ('Correspond', 'Samsvarar'),
    ('Ancient', 'Gamalt'),
    ('Marvel', 'Undur'),
    ('Feud', 'Deilur'),
    ('Reconstruction', 'Uppbygging'),
    ('Ambitions', 'Metnaður'),
    ('Destitute', 'Fátekur'),
    ('Evolution', 'Þróun'),
    ('Notorious', 'Illræmdur'),
    ('Blunder', 'Mistök'),
    ('Predator', 'Rándýr'),
    ('Prey', 'Bráð'),
    ('Excessive', 'Óhóflegt'),
    ('Intimidation', 'Ógn'),
    ('Relief', 'Léttir'),
    ('Devour', 'Gleypa í sig'),
    ('humble', 'Hógvær'),
    # unit 2
    ("sphere", "hnöttur"),
    ("perception", "skynjun"),
    ("constructive", "uppbygilegt"),
    ("chronic", "langvarandi"),
    ("audacity", "dirfska"),
    ("severe", "alvarlegt"),
    ("proportion", "hlutfall"),
    ("ancient", "gamalt"),
    ("phenomena", "fyrirbæri"),
    ("princible", "lögmál"),
    ("persist", "haldast eins halda áfram"),
    ("correspond", "samsvarar"),
    ("approach", "aðferð"),
    ("marvel", "undur"),
    ("feud", "deilur"),
    ("notorious", "illræmdur"),
    ("evolution", "þróun"),
    ("reconstruction", "uppbygging"),
    ("ambitions", "metnaður"),
    ("intimidation", "ógn"),
    ("prey", "bráð"),
    ("predator", "rándýr"),
    ("humble", "hógvær"),
    ("destitute", "fátekur"),
    ("relief", "léttir"),
    ("execessive", "óhóflegt"),
    ("devour", "gleypa í sig"),
    ("blunder", "mistök"),
    # unit 3
    ('neglect', 'vanrækja'),
    ('respiration', 'öndun'),
    ('durable', 'endingur'),
    ('demonstrate', 'sýna fram á'),
    ('repetition', 'endurtaka'),
    ('regulate', 'stjórna'),
    ('retention', 'varðveisla'),
    ('constant', 'stöðugur'),
    ('determine', 'ákveða'),
    ('generate', 'framleiða'),
    ('resistance', 'viðnám'),
    ('atrophy', 'rýrnun'),
    ('preserve', 'varðveita'),
    ('recuire', 'krefjast'),
    ('agitated', 'kvíðinn'),
    ('strain', 'álag'),
    ('stasis', 'stöðnun'),
    ('intuitive', 'innilegur'),
    ('motion', 'hreyfing'),
    ('concetration', 'einbeiting'),
    ('incompetence', 'ófærni'),
    ('discipline', 'aga'),
    ('compassion', 'samúð'),
    ('respond', 'svara'),
    ('misconception', 'misskilningur'),
    ('irrational', 'óröklegur'),
]


synomyms: list[tuple[str, str]] = [
    # Unit 1
    ('approach', 'method'),
    ('Phenomena', 'phenomenon'),
    ('Persist', 'continue'),
    ('Perception', 'awareness'),
    ('Audacity', 'boldness'),
    ('Sphere', 'orb'),
    ('Principle', 'law'),
    ('Constructive', 'positive'),
    ('Correspond', 'match'),
    ('Ancient', 'old'),
    ('Marvel', 'wonder'),
    ('Feud', 'dispute'),
    ('Reconstruction', 'rebuilding'),
    ('Ambitions', 'aspirations'),
    ('Destitute', 'poor'),
    ('Evolution', 'development'),
    ('Notorious', 'infamous'),
    ('Blunder', 'mistake'),
    ('Predator', 'carnivore'),
    ('Prey', 'victim'),
    ('Excessive', 'extreme'),
    ('Intimidation', 'threat'),
    ('Relief', 'comfort'),
    ('Devour', 'consume'),
    ('humble', 'modest'),
    # unit 2
    ("sphere", "orb"),
    ("perception", "awareness"),
    ("constructive", "positive"),
    ("chronic", "long-lasting"),
    ("audacity", "boldness"),
    ("severe", "serious"),
    ("proportion", "ratio"),
    ("ancient", "old"),
    ("phenomena", "phenomenon"),
    ("princible", "law"),
    ("persist", "continue"),
    ("correspond", "match"),
    ("approach", "method"),
    ("marvel", "wonder"),
    ("feud", "dispute"),
    ("notorious", "infamous"),
    ("evolution", "development"),
    ("reconstruction", "rebuilding"),
    ("ambitions", "aspirations"),
    ("intimidation", "threat"),
    ("prey", "victim"),
    ("predator", "carnivore"),
    ("humble", "modest"),
    ("destitute", "poor"),
    ("relief", "comfort"),
    ("execessive", "extreme"),
    ("devour", "consume"),
    ("blunder", "mistake"),
    # Unit 3
    ('neglect', 'disregard, ignore, neglect'),
    ('respiration', 'breathing, ventilation, respiration'),
    ('durable', 'lasting, enduring, strong'),
    ('demonstrate', 'show, exhibit, display'),
    ('repetition', 'reiteration, recurrence, repetition'),
    ('regulate', 'control, adjust, govern'),
    ('retention', 'preservation, conservation, retention'),
    ('constant', 'steady, unchanging, continuous'),
    ('determine', 'decide, resolve, conclude'),
    ('generate', 'produce, create, generate'),
    ('resistance', 'opposition, defiance, resistance'),
    ('atrophy', 'wasting, degeneration, atrophy'),
    ('preserve', 'conserve, protect, preserve'),
    ('recuire', 'need, demand, necessitate'),
    ('agitated', 'anxious, worried, upset'),
    ('strain', 'stress, tension, pressure'),
    ('stasis', 'standstill, stagnation, inactivity'),
    ('intuitive', 'instinctive, intuitive, inherent'),
    ('motion', 'movement, action, gesture'),
    ('concetration', 'consultation, discussion, deliberation'),
    ('incompetence', 'inability, incapability, incompetence'),
    ('discipline', 'self-control, training, discipline'),
    ('compassion', 'sympathy, pity, mercy'),
    ('respond', 'reply, answer, react'),
    ('misconception', 'misunderstanding, misapprehension, misconception'),
    ('irrational', 'unreasonable, illogical, irrational'),
]
